<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="$(AspireVersion)"/>

    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <OutputType>Exe</OutputType>
        <IsAspireHost>true</IsAspireHost>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost"/>
        <PackageReference Include="Aspire.Hosting.Docker"/>
        <PackageReference Include="Aspire.Hosting.PostgreSQL"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Sample.Silo\Sample.Silo.csproj"/>
        <ProjectReference Include="..\Sample.Api\Sample.Api.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Aspire.Orleans.Hosting\Shiny.Aspire.Orleans.Hosting.csproj"
                          IsAspireProjectResource="false"/>
        <ProjectReference Include="..\..\src\Shiny.Aspire.Hosting.Gluetun\Shiny.Aspire.Hosting.Gluetun.csproj"
                          IsAspireProjectResource="false"/>
        <ProjectReference Include="..\..\src\Shiny.Aspire.Hosting.Tunnel\Shiny.Aspire.Hosting.Tunnel.csproj"
                          IsAspireProjectResource="false"/>
        <ProjectReference Include="..\..\src\Shiny.Aspire.Hosting.Tunnel.Ssh\Shiny.Aspire.Hosting.Tunnel.Ssh.csproj"
                          IsAspireProjectResource="false"/>
        <ProjectReference Include="..\..\src\Shiny.Aspire.Hosting.Tunnel.Cloudflare\Shiny.Aspire.Hosting.Tunnel.Cloudflare.csproj"
                          IsAspireProjectResource="false"/>
    </ItemGroup>

</Project>
