<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Shouldly"/>
        <PackageReference Include="NSubstitute"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Shiny.Aspire.Hosting.Tunnel/Shiny.Aspire.Hosting.Tunnel.csproj"/>
        <ProjectReference Include="../../src/Shiny.Aspire.Hosting.Tunnel.Ssh/Shiny.Aspire.Hosting.Tunnel.Ssh.csproj"/>
        <ProjectReference Include="../../src/Shiny.Aspire.Hosting.Tunnel.AzureRelay/Shiny.Aspire.Hosting.Tunnel.AzureRelay.csproj"/>
        <ProjectReference Include="../../src/Shiny.Aspire.Hosting.Tunnel.Cloudflare/Shiny.Aspire.Hosting.Tunnel.Cloudflare.csproj"/>
        <ProjectReference Include="../../src/Shiny.Aspire.Hosting.Tunnel.Ngrok/Shiny.Aspire.Hosting.Tunnel.Ngrok.csproj"/>
    </ItemGroup>

</Project>
